[package]
name = "equito_bot"
version = "0.1.0"
edition = "2021"
readme = "README.md"


[[bin]]
name = "bot"
path = "src/main.rs"

[dependencies]
alloy = { version = "0.7.3", features = ["full"] }
eyre = "0.6.12"
futures-util = "0.3.31"
serde = { version = "1.0.215", features = ["derive"] } 
tokio = {version = "1.42.0", features = ["full"]}
