version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/scripts:/docker-entrypoint-initdb.d
    command: ["bash", "/docker-entrypoint-initdb.d/setup.sh"]

volumes:
  redis-data: